### ISSUE TITLE
Issue during setup

### ISSUE THREAD

**Issue by thebradleysanders** [Simple-Home/SimpleHome-Server#4]
While setting up the project, there seems to be a field called 'ota' missing from the users table.
Creating the error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ota' in 'field list'

Once I created the column the error went away.

**Comment by GamerClassN7** [comment]
> While setting up the project, there seems to be a field called 'ota' missing from the users table.
> Creating the error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ota' in 'field list'
> 
> Once I created the column the error went away.

Hi thanks for checking my project i am aware of this issue, most of time i am the one who set the server up :)

i am in middle of rewrite like i specified in attempt of contacting you.

can we contact each other in private so i can giwe you access to new version :)

what is your prefered way of contact ? email, discord, facebook ?

**Comment by thebradleysanders** [comment]
Yes, the best way to communicate would be through email. You can email me at TheBradleySanders@gmail.com

I will attempt to setup your project through the remastering branch. I will give you feedback. Do you have any installation instructions? If not I can do my best to install and document. I would like to talk to you about your goals for this project also. To see how I can help. Thank you.

**Comment by GamerClassN7** [comment]
Issue will be acounted for in nev V4
